package wordyApp;

/**
* wordyApp/AlreadyLoggedInHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class AlreadyLoggedInHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.AlreadyLoggedIn value = null;

  public AlreadyLoggedInHolder ()
  {
  }

  public AlreadyLoggedInHolder (wordyApp.AlreadyLoggedIn initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.AlreadyLoggedInHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.AlreadyLoggedInHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.AlreadyLoggedInHelper.type ();
  }

}
