package wordyApp;

/**
* wordyApp/Exceed10SecsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class Exceed10SecsHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.Exceed10Secs value = null;

  public Exceed10SecsHolder ()
  {
  }

  public Exceed10SecsHolder (wordyApp.Exceed10Secs initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.Exceed10SecsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.Exceed10SecsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.Exceed10SecsHelper.type ();
  }

}
