package wordyApp;


/**
* wordyApp/ExecutionException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class ExecutionException extends org.omg.CORBA.UserException
{
  public String message = null;

  public ExecutionException ()
  {
    super(ExecutionExceptionHelper.id());
  } // ctor

  public ExecutionException (String _message)
  {
    super(ExecutionExceptionHelper.id());
    message = _message;
  } // ctor


  public ExecutionException (String $reason, String _message)
  {
    super(ExecutionExceptionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class ExecutionException
