package wordyApp;

/**
* wordyApp/ExecutionExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class ExecutionExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.ExecutionException value = null;

  public ExecutionExceptionHolder ()
  {
  }

  public ExecutionExceptionHolder (wordyApp.ExecutionException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.ExecutionExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.ExecutionExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.ExecutionExceptionHelper.type ();
  }

}
