package wordyApp;


/**
* wordyApp/GameFull.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Thursday, May 11, 2023 4:39:48 PM SGT
*/

public final class GameFull extends org.omg.CORBA.UserException
{
  public String message = null;

  public GameFull ()
  {
    super(GameFullHelper.id());
  } // ctor

  public GameFull (String _message)
  {
    super(GameFullHelper.id());
    message = _message;
  } // ctor


  public GameFull (String $reason, String _message)
  {
    super(GameFullHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class GameFull
