package wordyApp;

/**
* wordyApp/GameFullHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Thursday, May 11, 2023 4:39:48 PM SGT
*/

public final class GameFullHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.GameFull value = null;

  public GameFullHolder ()
  {
  }

  public GameFullHolder (wordyApp.GameFull initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.GameFullHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.GameFullHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.GameFullHelper.type ();
  }

}
