package wordyApp;


/**
* wordyApp/IncorrectCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class IncorrectCredentials extends org.omg.CORBA.UserException
{
  public String message = null;

  public IncorrectCredentials ()
  {
    super(IncorrectCredentialsHelper.id());
  } // ctor

  public IncorrectCredentials (String _message)
  {
    super(IncorrectCredentialsHelper.id());
    message = _message;
  } // ctor


  public IncorrectCredentials (String $reason, String _message)
  {
    super(IncorrectCredentialsHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class IncorrectCredentials
