package wordyApp;

/**
* wordyApp/IncorrectCredentialsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class IncorrectCredentialsHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.IncorrectCredentials value = null;

  public IncorrectCredentialsHolder ()
  {
  }

  public IncorrectCredentialsHolder (wordyApp.IncorrectCredentials initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.IncorrectCredentialsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.IncorrectCredentialsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.IncorrectCredentialsHelper.type ();
  }

}
