package wordyApp;

/**
* wordyApp/InterruptedExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Saturday, June 10, 2023 4:40:53 AM SGT
*/

public final class InterruptedExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.InterruptedException value = null;

  public InterruptedExceptionHolder ()
  {
  }

  public InterruptedExceptionHolder (wordyApp.InterruptedException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.InterruptedExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.InterruptedExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.InterruptedExceptionHelper.type ();
  }

}
