package wordyApp;


/**
* wordyApp/LeaderBoard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class LeaderBoard implements org.omg.CORBA.portable.IDLEntity
{
  public int rank = (int)0;
  public String playerName = null;
  public int numberOfWins = (int)0;

  public LeaderBoard ()
  {
  } // ctor

  public LeaderBoard (int _rank, String _playerName, int _numberOfWins)
  {
    rank = _rank;
    playerName = _playerName;
    numberOfWins = _numberOfWins;
  } // ctor

} // class LeaderBoard
