package wordyApp;

/**
* wordyApp/LeaderBoardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class LeaderBoardHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.LeaderBoard value = null;

  public LeaderBoardHolder ()
  {
  }

  public LeaderBoardHolder (wordyApp.LeaderBoard initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.LeaderBoardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.LeaderBoardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.LeaderBoardHelper.type ();
  }

}
