package wordyApp;


/**
* wordyApp/ListOfWordsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Thursday, May 11, 2023 4:39:48 PM SGT
*/

public final class ListOfWordsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ListOfWordsHolder ()
  {
  }

  public ListOfWordsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.ListOfWordsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.ListOfWordsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.ListOfWordsHelper.type ();
  }

}
