package wordyApp;


/**
* wordyApp/LongestWordWinner.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class LongestWordWinner implements org.omg.CORBA.portable.IDLEntity
{
  public int wordLength = (int)0;
  public String playerName = null;
  public String longestWord = null;
  public int rank = (int)0;

  public LongestWordWinner ()
  {
  } // ctor

  public LongestWordWinner (int _wordLength, String _playerName, String _longestWord, int _rank)
  {
    wordLength = _wordLength;
    playerName = _playerName;
    longestWord = _longestWord;
    rank = _rank;
  } // ctor

} // class LongestWordWinner
