package wordyApp;

/**
* wordyApp/LongestWordWinnerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class LongestWordWinnerHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.LongestWordWinner value = null;

  public LongestWordWinnerHolder ()
  {
  }

  public LongestWordWinnerHolder (wordyApp.LongestWordWinner initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.LongestWordWinnerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.LongestWordWinnerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.LongestWordWinnerHelper.type ();
  }

}
