package wordyApp;


/**
* wordyApp/NoPlayerJoined.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class NoPlayerJoined extends org.omg.CORBA.UserException
{
  public String message = null;

  public NoPlayerJoined ()
  {
    super(NoPlayerJoinedHelper.id());
  } // ctor

  public NoPlayerJoined (String _message)
  {
    super(NoPlayerJoinedHelper.id());
    message = _message;
  } // ctor


  public NoPlayerJoined (String $reason, String _message)
  {
    super(NoPlayerJoinedHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NoPlayerJoined
