package wordyApp;

/**
* wordyApp/NotPartOf17LettersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class NotPartOf17LettersHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.NotPartOf17Letters value = null;

  public NotPartOf17LettersHolder ()
  {
  }

  public NotPartOf17LettersHolder (wordyApp.NotPartOf17Letters initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.NotPartOf17LettersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.NotPartOf17LettersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.NotPartOf17LettersHelper.type ();
  }

}
