package wordyApp;


/**
* wordyApp/NotPartOf17Letters.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class NotPartOf17Letters extends org.omg.CORBA.UserException
{
  public String message = null;

  public NotPartOf17Letters ()
  {
    super(NotPartOf17LettersHelper.id());
  } // ctor

  public NotPartOf17Letters (String _message)
  {
    super(NotPartOf17LettersHelper.id());
    message = _message;
  } // ctor


  public NotPartOf17Letters (String $reason, String _message)
  {
    super(NotPartOf17LettersHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NotPartOf17Letters
