package wordyApp;


/**
* wordyApp/NoWinner.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class NoWinner extends org.omg.CORBA.UserException
{
  public String message = null;

  public NoWinner ()
  {
    super(NoWinnerHelper.id());
  } // ctor

  public NoWinner (String _message)
  {
    super(NoWinnerHelper.id());
    message = _message;
  } // ctor


  public NoWinner (String $reason, String _message)
  {
    super(NoWinnerHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class NoWinner
