package wordyApp;

/**
* wordyApp/NoWinnerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class NoWinnerHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.NoWinner value = null;

  public NoWinnerHolder ()
  {
  }

  public NoWinnerHolder (wordyApp.NoWinner initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.NoWinnerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.NoWinnerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.NoWinnerHelper.type ();
  }

}
