package wordyApp;


/**
* wordyApp/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class Player implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public String password = null;
  public boolean loggedIn = false;
  public boolean isInGame = false;
  public int roundsWon = (int)0;

  public Player ()
  {
  } // ctor

  public Player (String _username, String _password, boolean _loggedIn, boolean _isInGame, int _roundsWon)
  {
    username = _username;
    password = _password;
    loggedIn = _loggedIn;
    isInGame = _isInGame;
    roundsWon = _roundsWon;
  } // ctor

} // class Player
