package wordyApp;


/**
* wordyApp/PlayerListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class PlayerListHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.Player value[] = null;

  public PlayerListHolder ()
  {
  }

  public PlayerListHolder (wordyApp.Player[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.PlayerListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.PlayerListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.PlayerListHelper.type ();
  }

}
