package wordyApp;


/**
* wordyApp/PlayerWordsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Saturday, June 10, 2023 4:46:24 AM SGT
*/

public final class PlayerWordsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public PlayerWordsHolder ()
  {
  }

  public PlayerWordsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.PlayerWordsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.PlayerWordsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.PlayerWordsHelper.type ();
  }

}
