package wordyApp;


/**
* wordyApp/RoomGameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

abstract public class RoomGameHelper
{
  private static String  _id = "IDL:wordyApp/RoomGame:1.0";

  public static void insert (org.omg.CORBA.Any a, wordyApp.RoomGame that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static wordyApp.RoomGame extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "gameRoomID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "gameState",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "roomRLetters",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "roundsWonIncr",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "winner",
            _tcOf_members0,
            null);
          _tcOf_members0 = wordyApp.PlayerHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (wordyApp.PlayerListHelper.id (), "PlayerList", _tcOf_members0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "players",
            _tcOf_members0,
            null);
          _tcOf_members0 = wordyApp.WordHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (wordyApp.WordListHelper.id (), "WordList", _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "submittedWords",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (wordyApp.RoomGameHelper.id (), "RoomGame", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static wordyApp.RoomGame read (org.omg.CORBA.portable.InputStream istream)
  {
    wordyApp.RoomGame value = new wordyApp.RoomGame ();
    value.gameRoomID = istream.read_string ();
    value.gameState = istream.read_string ();
    value.roomRLetters = istream.read_string ();
    value.roundsWonIncr = istream.read_boolean ();
    value.winner = istream.read_string ();
    value.players = wordyApp.PlayerListHelper.read (istream);
    value.submittedWords = wordyApp.WordListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, wordyApp.RoomGame value)
  {
    ostream.write_string (value.gameRoomID);
    ostream.write_string (value.gameState);
    ostream.write_string (value.roomRLetters);
    ostream.write_boolean (value.roundsWonIncr);
    ostream.write_string (value.winner);
    wordyApp.PlayerListHelper.write (ostream, value.players);
    wordyApp.WordListHelper.write (ostream, value.submittedWords);
  }

}
