package wordyApp;

/**
* wordyApp/RoomGameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class RoomGameHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.RoomGame value = null;

  public RoomGameHolder ()
  {
  }

  public RoomGameHolder (wordyApp.RoomGame initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.RoomGameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.RoomGameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.RoomGameHelper.type ();
  }

}
