package wordyApp;


/**
* wordyApp/RoundEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class RoundEnd extends org.omg.CORBA.UserException
{
  public String message = null;

  public RoundEnd ()
  {
    super(RoundEndHelper.id());
  } // ctor

  public RoundEnd (String _message)
  {
    super(RoundEndHelper.id());
    message = _message;
  } // ctor


  public RoundEnd (String $reason, String _message)
  {
    super(RoundEndHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class RoundEnd
