package wordyApp;


/**
* wordyApp/TieResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class TieResult extends org.omg.CORBA.UserException
{
  public String message = null;

  public TieResult ()
  {
    super(TieResultHelper.id());
  } // ctor

  public TieResult (String _message)
  {
    super(TieResultHelper.id());
    message = _message;
  } // ctor


  public TieResult (String $reason, String _message)
  {
    super(TieResultHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class TieResult
