package wordyApp;

/**
* wordyApp/TieResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class TieResultHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.TieResult value = null;

  public TieResultHolder ()
  {
  }

  public TieResultHolder (wordyApp.TieResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.TieResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.TieResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.TieResultHelper.type ();
  }

}
