package wordyApp;


/**
* wordyApp/UserNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class UserNotFound extends org.omg.CORBA.UserException
{
  public String message = null;

  public UserNotFound ()
  {
    super(UserNotFoundHelper.id());
  } // ctor

  public UserNotFound (String _message)
  {
    super(UserNotFoundHelper.id());
    message = _message;
  } // ctor


  public UserNotFound (String $reason, String _message)
  {
    super(UserNotFoundHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class UserNotFound
