package wordyApp;


/**
* wordyApp/WordsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, April 28, 2023 8:11:38 AM SGT
*/


// defining sequence of strings == List<> in java
public final class WordsHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public WordsHolder ()
  {
  }

  public WordsHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.WordsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.WordsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.WordsHelper.type ();
  }

}
