package wordyApp;

/**
* wordyApp/WordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class WordHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.Word value = null;

  public WordHolder ()
  {
  }

  public WordHolder (wordyApp.Word initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.WordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.WordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.WordHelper.type ();
  }

}
