package wordyApp;


/**
* wordyApp/Word.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class Word implements org.omg.CORBA.portable.IDLEntity
{
  public String wordPrompt = null;
  public wordyApp.Player wordOwner = null;

  public Word ()
  {
  } // ctor

  public Word (String _wordPrompt, wordyApp.Player _wordOwner)
  {
    wordPrompt = _wordPrompt;
    wordOwner = _wordOwner;
  } // ctor

} // class Word
