package wordyApp;


/**
* wordyApp/WordyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/


// SERVER TO CLIENT METHODS
abstract public class WordyHelper
{
  private static String  _id = "IDL:wordyApp/Wordy:1.0";

  public static void insert (org.omg.CORBA.Any a, wordyApp.Wordy that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static wordyApp.Wordy extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (wordyApp.WordyHelper.id (), "Wordy");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static wordyApp.Wordy read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_WordyStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, wordyApp.Wordy value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static wordyApp.Wordy narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof wordyApp.Wordy)
      return (wordyApp.Wordy)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      wordyApp._WordyStub stub = new wordyApp._WordyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static wordyApp.Wordy unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof wordyApp.Wordy)
      return (wordyApp.Wordy)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      wordyApp._WordyStub stub = new wordyApp._WordyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
