package wordyApp;

/**
* wordyApp/WordyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/


// SERVER TO CLIENT METHODS
public final class WordyHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.Wordy value = null;

  public WordyHolder ()
  {
  }

  public WordyHolder (wordyApp.Wordy initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.WordyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.WordyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.WordyHelper.type ();
  }

}
