package wordyApp;


/**
* wordyApp/WordListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/

public final class WordListHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.Word value[] = null;

  public WordListHolder ()
  {
  }

  public WordListHolder (wordyApp.Word[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.WordListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.WordListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.WordListHelper.type ();
  }

}
