package wordyApp.WordyPackage;


/**
* wordyApp/WordyPackage/hallOfFameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/


/* Displays leading players */
public final class hallOfFameHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.LeaderBoard value[] = null;

  public hallOfFameHolder ()
  {
  }

  public hallOfFameHolder (wordyApp.LeaderBoard[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.WordyPackage.hallOfFameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.WordyPackage.hallOfFameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.WordyPackage.hallOfFameHelper.type ();
  }

}
