package wordyApp.WordyPackage;


/**
* wordyApp/WordyPackage/leaderBoardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, May 14, 2023 5:54:57 AM SGT
*/


/*
            // uses ArrayList
            // top players
            */
public final class leaderBoardHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.LeaderBoard value[] = null;

  public leaderBoardHolder ()
  {
  }

  public leaderBoardHolder (wordyApp.LeaderBoard[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.WordyPackage.leaderBoardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.WordyPackage.leaderBoardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.WordyPackage.leaderBoardHelper.type ();
  }

}
