package wordyApp.WordyPackage;


/**
* wordyApp/WordyPackage/longestWinnerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/


/* Displays top 5 longest words*/
abstract public class longestWinnerHelper
{
  private static String  _id = "IDL:wordyApp/Wordy/longestWinner:1.0";

  public static void insert (org.omg.CORBA.Any a, wordyApp.LongestWordWinner[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static wordyApp.LongestWordWinner[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = wordyApp.LongestWordWinnerHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (wordyApp.WordyPackage.longestWinnerHelper.id (), "longestWinner", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static wordyApp.LongestWordWinner[] read (org.omg.CORBA.portable.InputStream istream)
  {
    wordyApp.LongestWordWinner value[] = null;
    int _len0 = istream.read_long ();
    value = new wordyApp.LongestWordWinner[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = wordyApp.LongestWordWinnerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, wordyApp.LongestWordWinner[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      wordyApp.LongestWordWinnerHelper.write (ostream, value[_i0]);
  }

}
