package wordyApp.WordyPackage;


/**
* wordyApp/WordyPackage/longestWinnerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Friday, July 7, 2023 7:38:10 PM SGT
*/


/* Displays top 5 longest words*/
public final class longestWinnerHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyApp.LongestWordWinner value[] = null;

  public longestWinnerHolder ()
  {
  }

  public longestWinnerHolder (wordyApp.LongestWordWinner[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyApp.WordyPackage.longestWinnerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyApp.WordyPackage.longestWinnerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyApp.WordyPackage.longestWinnerHelper.type ();
  }

}
