# Python stubs generated by omniidl from Wordy.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "wordyApp"
#
__name__ = "wordyApp"
_0_wordyApp = omniORB.openModule("wordyApp", r"Wordy.idl")
_0_wordyApp__POA = omniORB.openModule("wordyApp__POA", r"Wordy.idl")


# struct Player
_0_wordyApp.Player = omniORB.newEmptyClass()
class Player (omniORB.StructBase):
    _NP_RepositoryId = "IDL:wordyApp/Player:1.0"

    def __init__(self, username, password, loggedIn, isInGame, roundsWon):
        self.username = username
        self.password = password
        self.loggedIn = loggedIn
        self.isInGame = isInGame
        self.roundsWon = roundsWon

_0_wordyApp.Player = Player
_0_wordyApp._d_Player  = (omniORB.tcInternal.tv_struct, Player, Player._NP_RepositoryId, "Player", "username", (omniORB.tcInternal.tv_string,0), "password", (omniORB.tcInternal.tv_string,0), "loggedIn", omniORB.tcInternal.tv_boolean, "isInGame", omniORB.tcInternal.tv_boolean, "roundsWon", omniORB.tcInternal.tv_long)
_0_wordyApp._tc_Player = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_Player)
omniORB.registerType(Player._NP_RepositoryId, _0_wordyApp._d_Player, _0_wordyApp._tc_Player)
del Player

# typedef ... PlayerList
class PlayerList:
    _NP_RepositoryId = "IDL:wordyApp/PlayerList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordyApp.PlayerList = PlayerList
_0_wordyApp._d_PlayerList  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyApp/Player:1.0"], 0)
_0_wordyApp._ad_PlayerList = (omniORB.tcInternal.tv_alias, PlayerList._NP_RepositoryId, "PlayerList", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyApp/Player:1.0"], 0))
_0_wordyApp._tc_PlayerList = omniORB.tcInternal.createTypeCode(_0_wordyApp._ad_PlayerList)
omniORB.registerType(PlayerList._NP_RepositoryId, _0_wordyApp._ad_PlayerList, _0_wordyApp._tc_PlayerList)
del PlayerList

# struct Word
_0_wordyApp.Word = omniORB.newEmptyClass()
class Word (omniORB.StructBase):
    _NP_RepositoryId = "IDL:wordyApp/Word:1.0"

    def __init__(self, wordPrompt, wordOwner):
        self.wordPrompt = wordPrompt
        self.wordOwner = wordOwner

_0_wordyApp.Word = Word
_0_wordyApp._d_Word  = (omniORB.tcInternal.tv_struct, Word, Word._NP_RepositoryId, "Word", "wordPrompt", (omniORB.tcInternal.tv_string,0), "wordOwner", omniORB.typeMapping["IDL:wordyApp/Player:1.0"])
_0_wordyApp._tc_Word = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_Word)
omniORB.registerType(Word._NP_RepositoryId, _0_wordyApp._d_Word, _0_wordyApp._tc_Word)
del Word

# typedef ... WordList
class WordList:
    _NP_RepositoryId = "IDL:wordyApp/WordList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordyApp.WordList = WordList
_0_wordyApp._d_WordList  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyApp/Word:1.0"], 0)
_0_wordyApp._ad_WordList = (omniORB.tcInternal.tv_alias, WordList._NP_RepositoryId, "WordList", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyApp/Word:1.0"], 0))
_0_wordyApp._tc_WordList = omniORB.tcInternal.createTypeCode(_0_wordyApp._ad_WordList)
omniORB.registerType(WordList._NP_RepositoryId, _0_wordyApp._ad_WordList, _0_wordyApp._tc_WordList)
del WordList

# struct RoomGame
_0_wordyApp.RoomGame = omniORB.newEmptyClass()
class RoomGame (omniORB.StructBase):
    _NP_RepositoryId = "IDL:wordyApp/RoomGame:1.0"

    def __init__(self, gameRoomID, gameState, roomRLetters, roundsWonIncr, winner, players, submittedWords):
        self.gameRoomID = gameRoomID
        self.gameState = gameState
        self.roomRLetters = roomRLetters
        self.roundsWonIncr = roundsWonIncr
        self.winner = winner
        self.players = players
        self.submittedWords = submittedWords

_0_wordyApp.RoomGame = RoomGame
_0_wordyApp._d_RoomGame  = (omniORB.tcInternal.tv_struct, RoomGame, RoomGame._NP_RepositoryId, "RoomGame", "gameRoomID", (omniORB.tcInternal.tv_string,0), "gameState", (omniORB.tcInternal.tv_string,0), "roomRLetters", (omniORB.tcInternal.tv_string,0), "roundsWonIncr", omniORB.tcInternal.tv_boolean, "winner", (omniORB.tcInternal.tv_string,0), "players", omniORB.typeMapping["IDL:wordyApp/PlayerList:1.0"], "submittedWords", omniORB.typeMapping["IDL:wordyApp/WordList:1.0"])
_0_wordyApp._tc_RoomGame = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_RoomGame)
omniORB.registerType(RoomGame._NP_RepositoryId, _0_wordyApp._d_RoomGame, _0_wordyApp._tc_RoomGame)
del RoomGame

# struct LeaderBoard
_0_wordyApp.LeaderBoard = omniORB.newEmptyClass()
class LeaderBoard (omniORB.StructBase):
    _NP_RepositoryId = "IDL:wordyApp/LeaderBoard:1.0"

    def __init__(self, rank, playerName, numberOfWins):
        self.rank = rank
        self.playerName = playerName
        self.numberOfWins = numberOfWins

_0_wordyApp.LeaderBoard = LeaderBoard
_0_wordyApp._d_LeaderBoard  = (omniORB.tcInternal.tv_struct, LeaderBoard, LeaderBoard._NP_RepositoryId, "LeaderBoard", "rank", omniORB.tcInternal.tv_long, "playerName", (omniORB.tcInternal.tv_string,0), "numberOfWins", omniORB.tcInternal.tv_long)
_0_wordyApp._tc_LeaderBoard = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_LeaderBoard)
omniORB.registerType(LeaderBoard._NP_RepositoryId, _0_wordyApp._d_LeaderBoard, _0_wordyApp._tc_LeaderBoard)
del LeaderBoard

# struct LongestWordWinner
_0_wordyApp.LongestWordWinner = omniORB.newEmptyClass()
class LongestWordWinner (omniORB.StructBase):
    _NP_RepositoryId = "IDL:wordyApp/LongestWordWinner:1.0"

    def __init__(self, wordLength, playerName, longestWord, rank):
        self.wordLength = wordLength
        self.playerName = playerName
        self.longestWord = longestWord
        self.rank = rank

_0_wordyApp.LongestWordWinner = LongestWordWinner
_0_wordyApp._d_LongestWordWinner  = (omniORB.tcInternal.tv_struct, LongestWordWinner, LongestWordWinner._NP_RepositoryId, "LongestWordWinner", "wordLength", omniORB.tcInternal.tv_long, "playerName", (omniORB.tcInternal.tv_string,0), "longestWord", (omniORB.tcInternal.tv_string,0), "rank", omniORB.tcInternal.tv_long)
_0_wordyApp._tc_LongestWordWinner = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_LongestWordWinner)
omniORB.registerType(LongestWordWinner._NP_RepositoryId, _0_wordyApp._d_LongestWordWinner, _0_wordyApp._tc_LongestWordWinner)
del LongestWordWinner

# exception AlreadyLoggedIn
_0_wordyApp.AlreadyLoggedIn = omniORB.newEmptyClass()
class AlreadyLoggedIn (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/AlreadyLoggedIn:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.AlreadyLoggedIn = AlreadyLoggedIn
_0_wordyApp._d_AlreadyLoggedIn  = (omniORB.tcInternal.tv_except, AlreadyLoggedIn, AlreadyLoggedIn._NP_RepositoryId, "AlreadyLoggedIn", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_AlreadyLoggedIn = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_AlreadyLoggedIn)
omniORB.registerType(AlreadyLoggedIn._NP_RepositoryId, _0_wordyApp._d_AlreadyLoggedIn, _0_wordyApp._tc_AlreadyLoggedIn)
del AlreadyLoggedIn

# exception IncorrectCredentials
_0_wordyApp.IncorrectCredentials = omniORB.newEmptyClass()
class IncorrectCredentials (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/IncorrectCredentials:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.IncorrectCredentials = IncorrectCredentials
_0_wordyApp._d_IncorrectCredentials  = (omniORB.tcInternal.tv_except, IncorrectCredentials, IncorrectCredentials._NP_RepositoryId, "IncorrectCredentials", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_IncorrectCredentials = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_IncorrectCredentials)
omniORB.registerType(IncorrectCredentials._NP_RepositoryId, _0_wordyApp._d_IncorrectCredentials, _0_wordyApp._tc_IncorrectCredentials)
del IncorrectCredentials

# exception InvalidWord
_0_wordyApp.InvalidWord = omniORB.newEmptyClass()
class InvalidWord (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/InvalidWord:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.InvalidWord = InvalidWord
_0_wordyApp._d_InvalidWord  = (omniORB.tcInternal.tv_except, InvalidWord, InvalidWord._NP_RepositoryId, "InvalidWord", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_InvalidWord = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_InvalidWord)
omniORB.registerType(InvalidWord._NP_RepositoryId, _0_wordyApp._d_InvalidWord, _0_wordyApp._tc_InvalidWord)
del InvalidWord

# exception NoPlayerJoined
_0_wordyApp.NoPlayerJoined = omniORB.newEmptyClass()
class NoPlayerJoined (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/NoPlayerJoined:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.NoPlayerJoined = NoPlayerJoined
_0_wordyApp._d_NoPlayerJoined  = (omniORB.tcInternal.tv_except, NoPlayerJoined, NoPlayerJoined._NP_RepositoryId, "NoPlayerJoined", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_NoPlayerJoined = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_NoPlayerJoined)
omniORB.registerType(NoPlayerJoined._NP_RepositoryId, _0_wordyApp._d_NoPlayerJoined, _0_wordyApp._tc_NoPlayerJoined)
del NoPlayerJoined

# exception RoundEnd
_0_wordyApp.RoundEnd = omniORB.newEmptyClass()
class RoundEnd (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/RoundEnd:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.RoundEnd = RoundEnd
_0_wordyApp._d_RoundEnd  = (omniORB.tcInternal.tv_except, RoundEnd, RoundEnd._NP_RepositoryId, "RoundEnd", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_RoundEnd = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_RoundEnd)
omniORB.registerType(RoundEnd._NP_RepositoryId, _0_wordyApp._d_RoundEnd, _0_wordyApp._tc_RoundEnd)
del RoundEnd

# exception NotPartOf17Letters
_0_wordyApp.NotPartOf17Letters = omniORB.newEmptyClass()
class NotPartOf17Letters (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/NotPartOf17Letters:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.NotPartOf17Letters = NotPartOf17Letters
_0_wordyApp._d_NotPartOf17Letters  = (omniORB.tcInternal.tv_except, NotPartOf17Letters, NotPartOf17Letters._NP_RepositoryId, "NotPartOf17Letters", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_NotPartOf17Letters = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_NotPartOf17Letters)
omniORB.registerType(NotPartOf17Letters._NP_RepositoryId, _0_wordyApp._d_NotPartOf17Letters, _0_wordyApp._tc_NotPartOf17Letters)
del NotPartOf17Letters

# exception Exceed10Secs
_0_wordyApp.Exceed10Secs = omniORB.newEmptyClass()
class Exceed10Secs (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/Exceed10Secs:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.Exceed10Secs = Exceed10Secs
_0_wordyApp._d_Exceed10Secs  = (omniORB.tcInternal.tv_except, Exceed10Secs, Exceed10Secs._NP_RepositoryId, "Exceed10Secs", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_Exceed10Secs = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_Exceed10Secs)
omniORB.registerType(Exceed10Secs._NP_RepositoryId, _0_wordyApp._d_Exceed10Secs, _0_wordyApp._tc_Exceed10Secs)
del Exceed10Secs

# exception UserNotFound
_0_wordyApp.UserNotFound = omniORB.newEmptyClass()
class UserNotFound (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/UserNotFound:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.UserNotFound = UserNotFound
_0_wordyApp._d_UserNotFound  = (omniORB.tcInternal.tv_except, UserNotFound, UserNotFound._NP_RepositoryId, "UserNotFound", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_UserNotFound = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_UserNotFound)
omniORB.registerType(UserNotFound._NP_RepositoryId, _0_wordyApp._d_UserNotFound, _0_wordyApp._tc_UserNotFound)
del UserNotFound

# exception ExecutionException
_0_wordyApp.ExecutionException = omniORB.newEmptyClass()
class ExecutionException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/ExecutionException:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.ExecutionException = ExecutionException
_0_wordyApp._d_ExecutionException  = (omniORB.tcInternal.tv_except, ExecutionException, ExecutionException._NP_RepositoryId, "ExecutionException", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_ExecutionException = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_ExecutionException)
omniORB.registerType(ExecutionException._NP_RepositoryId, _0_wordyApp._d_ExecutionException, _0_wordyApp._tc_ExecutionException)
del ExecutionException

# exception NoWinner
_0_wordyApp.NoWinner = omniORB.newEmptyClass()
class NoWinner (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/NoWinner:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.NoWinner = NoWinner
_0_wordyApp._d_NoWinner  = (omniORB.tcInternal.tv_except, NoWinner, NoWinner._NP_RepositoryId, "NoWinner", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_NoWinner = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_NoWinner)
omniORB.registerType(NoWinner._NP_RepositoryId, _0_wordyApp._d_NoWinner, _0_wordyApp._tc_NoWinner)
del NoWinner

# exception TieResult
_0_wordyApp.TieResult = omniORB.newEmptyClass()
class TieResult (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyApp/TieResult:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyApp.TieResult = TieResult
_0_wordyApp._d_TieResult  = (omniORB.tcInternal.tv_except, TieResult, TieResult._NP_RepositoryId, "TieResult", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyApp._tc_TieResult = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_TieResult)
omniORB.registerType(TieResult._NP_RepositoryId, _0_wordyApp._d_TieResult, _0_wordyApp._tc_TieResult)
del TieResult

# interface Wordy
_0_wordyApp._d_Wordy = (omniORB.tcInternal.tv_objref, "IDL:wordyApp/Wordy:1.0", "Wordy")
omniORB.typeMapping["IDL:wordyApp/Wordy:1.0"] = _0_wordyApp._d_Wordy
_0_wordyApp.Wordy = omniORB.newEmptyClass()
class Wordy :
    _NP_RepositoryId = _0_wordyApp._d_Wordy[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil

    
    # typedef ... hallOfFame
    class hallOfFame:
        _NP_RepositoryId = "IDL:wordyApp/Wordy/hallOfFame:1.0"
        def __init__(self, *args, **kw):
            raise RuntimeError("Cannot construct objects of this type.")
    _d_hallOfFame  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyApp/LeaderBoard:1.0"], 0)
    _ad_hallOfFame = (omniORB.tcInternal.tv_alias, hallOfFame._NP_RepositoryId, "hallOfFame", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyApp/LeaderBoard:1.0"], 0))
    _tc_hallOfFame = omniORB.tcInternal.createTypeCode(_ad_hallOfFame)
    omniORB.registerType(hallOfFame._NP_RepositoryId, _ad_hallOfFame, _tc_hallOfFame)
    
    # typedef ... longestWinner
    class longestWinner:
        _NP_RepositoryId = "IDL:wordyApp/Wordy/longestWinner:1.0"
        def __init__(self, *args, **kw):
            raise RuntimeError("Cannot construct objects of this type.")
    _d_longestWinner  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyApp/LongestWordWinner:1.0"], 0)
    _ad_longestWinner = (omniORB.tcInternal.tv_alias, longestWinner._NP_RepositoryId, "longestWinner", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyApp/LongestWordWinner:1.0"], 0))
    _tc_longestWinner = omniORB.tcInternal.createTypeCode(_ad_longestWinner)
    omniORB.registerType(longestWinner._NP_RepositoryId, _ad_longestWinner, _tc_longestWinner)


_0_wordyApp.Wordy = Wordy
_0_wordyApp._tc_Wordy = omniORB.tcInternal.createTypeCode(_0_wordyApp._d_Wordy)
omniORB.registerType(Wordy._NP_RepositoryId, _0_wordyApp._d_Wordy, _0_wordyApp._tc_Wordy)

# Wordy operations and attributes
Wordy._d_login = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.typeMapping["IDL:wordyApp/Player:1.0"], ), {_0_wordyApp.IncorrectCredentials._NP_RepositoryId: _0_wordyApp._d_IncorrectCredentials, _0_wordyApp.AlreadyLoggedIn._NP_RepositoryId: _0_wordyApp._d_AlreadyLoggedIn})
Wordy._d_showLeaderBoard = ((), (omniORB.typeMapping["IDL:wordyApp/Wordy/hallOfFame:1.0"], ), None)
Wordy._d_top5longestWords = ((), (omniORB.typeMapping["IDL:wordyApp/Wordy/longestWinner:1.0"], ), None)
Wordy._d_play = ((omniORB.typeMapping["IDL:wordyApp/Player:1.0"], ), (omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"], ), {_0_wordyApp.NoPlayerJoined._NP_RepositoryId: _0_wordyApp._d_NoPlayerJoined})
Wordy._d_nextRoundHandler = ((omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"], ), (omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"], ), None)
Wordy._d_startTenSecondTimer = ((omniORB.tcInternal.tv_long, ), (), None)
Wordy._d_startRoundTimer = ((omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"], omniORB.tcInternal.tv_long), (), None)
Wordy._d_startBreakTimer = ((omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"], ), (), None)
Wordy._d_getRoundTimer = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_longlong, ), None)
Wordy._d_getBreakTimer = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_longlong, ), None)
Wordy._d_addRoom = (((omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"]), (), None)
Wordy._d_decreasePlayerCount = (((omniORB.tcInternal.tv_string,0), ), (), None)
Wordy._d_deleteRoom = (((omniORB.tcInternal.tv_string,0), ), (), None)
Wordy._d_updatePlayerIsInGame = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_boolean), (), None)
Wordy._d_updateResult = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), (), None)
Wordy._d_getWinner = (((omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long), ((omniORB.tcInternal.tv_string,0), ), None)
Wordy._d_getPlayerCount = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_long, ), None)
Wordy._d_calculateTimeLeft = ((omniORB.tcInternal.tv_longlong, omniORB.tcInternal.tv_longlong), (omniORB.tcInternal.tv_longlong, ), None)
Wordy._d_getTimeLeft = ((), (omniORB.tcInternal.tv_longlong, ), None)
Wordy._d_setRandomLetters = ((omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"], ), (), None)
Wordy._d_getRoomRandomLetters = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
Wordy._d_userEnteredWord = (((omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:wordyApp/Player:1.0"], omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"]), (omniORB.tcInternal.tv_boolean, ), None)
Wordy._d_roundWinnerChecker = ((omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"], ), (omniORB.typeMapping["IDL:wordyApp/Player:1.0"], ), {_0_wordyApp.NoWinner._NP_RepositoryId: _0_wordyApp._d_NoWinner, _0_wordyApp.TieResult._NP_RepositoryId: _0_wordyApp._d_TieResult})
Wordy._d_gameWinStateChecker = ((omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"], ), (omniORB.tcInternal.tv_boolean, ), None)
Wordy._d_getGameWinner = ((omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"], ), (omniORB.typeMapping["IDL:wordyApp/Player:1.0"], ), None)
Wordy._d_finishGame = ((omniORB.typeMapping["IDL:wordyApp/Player:1.0"], omniORB.typeMapping["IDL:wordyApp/RoomGame:1.0"]), (), None)
Wordy._d_logOffUser = (((omniORB.tcInternal.tv_string,0), ), (), {_0_wordyApp.UserNotFound._NP_RepositoryId: _0_wordyApp._d_UserNotFound})

# Wordy object reference
class _objref_Wordy (CORBA.Object):
    _NP_RepositoryId = Wordy._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def login(self, *args):
        return self._obj.invoke("login", _0_wordyApp.Wordy._d_login, args)

    def showLeaderBoard(self, *args):
        return self._obj.invoke("showLeaderBoard", _0_wordyApp.Wordy._d_showLeaderBoard, args)

    def top5longestWords(self, *args):
        return self._obj.invoke("top5longestWords", _0_wordyApp.Wordy._d_top5longestWords, args)

    def play(self, *args):
        return self._obj.invoke("play", _0_wordyApp.Wordy._d_play, args)

    def nextRoundHandler(self, *args):
        return self._obj.invoke("nextRoundHandler", _0_wordyApp.Wordy._d_nextRoundHandler, args)

    def startTenSecondTimer(self, *args):
        return self._obj.invoke("startTenSecondTimer", _0_wordyApp.Wordy._d_startTenSecondTimer, args)

    def startRoundTimer(self, *args):
        return self._obj.invoke("startRoundTimer", _0_wordyApp.Wordy._d_startRoundTimer, args)

    def startBreakTimer(self, *args):
        return self._obj.invoke("startBreakTimer", _0_wordyApp.Wordy._d_startBreakTimer, args)

    def getRoundTimer(self, *args):
        return self._obj.invoke("getRoundTimer", _0_wordyApp.Wordy._d_getRoundTimer, args)

    def getBreakTimer(self, *args):
        return self._obj.invoke("getBreakTimer", _0_wordyApp.Wordy._d_getBreakTimer, args)

    def addRoom(self, *args):
        return self._obj.invoke("addRoom", _0_wordyApp.Wordy._d_addRoom, args)

    def decreasePlayerCount(self, *args):
        return self._obj.invoke("decreasePlayerCount", _0_wordyApp.Wordy._d_decreasePlayerCount, args)

    def deleteRoom(self, *args):
        return self._obj.invoke("deleteRoom", _0_wordyApp.Wordy._d_deleteRoom, args)

    def updatePlayerIsInGame(self, *args):
        return self._obj.invoke("updatePlayerIsInGame", _0_wordyApp.Wordy._d_updatePlayerIsInGame, args)

    def updateResult(self, *args):
        return self._obj.invoke("updateResult", _0_wordyApp.Wordy._d_updateResult, args)

    def getWinner(self, *args):
        return self._obj.invoke("getWinner", _0_wordyApp.Wordy._d_getWinner, args)

    def getPlayerCount(self, *args):
        return self._obj.invoke("getPlayerCount", _0_wordyApp.Wordy._d_getPlayerCount, args)

    def calculateTimeLeft(self, *args):
        return self._obj.invoke("calculateTimeLeft", _0_wordyApp.Wordy._d_calculateTimeLeft, args)

    def getTimeLeft(self, *args):
        return self._obj.invoke("getTimeLeft", _0_wordyApp.Wordy._d_getTimeLeft, args)

    def setRandomLetters(self, *args):
        return self._obj.invoke("setRandomLetters", _0_wordyApp.Wordy._d_setRandomLetters, args)

    def getRoomRandomLetters(self, *args):
        return self._obj.invoke("getRoomRandomLetters", _0_wordyApp.Wordy._d_getRoomRandomLetters, args)

    def userEnteredWord(self, *args):
        return self._obj.invoke("userEnteredWord", _0_wordyApp.Wordy._d_userEnteredWord, args)

    def roundWinnerChecker(self, *args):
        return self._obj.invoke("roundWinnerChecker", _0_wordyApp.Wordy._d_roundWinnerChecker, args)

    def gameWinStateChecker(self, *args):
        return self._obj.invoke("gameWinStateChecker", _0_wordyApp.Wordy._d_gameWinStateChecker, args)

    def getGameWinner(self, *args):
        return self._obj.invoke("getGameWinner", _0_wordyApp.Wordy._d_getGameWinner, args)

    def finishGame(self, *args):
        return self._obj.invoke("finishGame", _0_wordyApp.Wordy._d_finishGame, args)

    def logOffUser(self, *args):
        return self._obj.invoke("logOffUser", _0_wordyApp.Wordy._d_logOffUser, args)

omniORB.registerObjref(Wordy._NP_RepositoryId, _objref_Wordy)
_0_wordyApp._objref_Wordy = _objref_Wordy
del Wordy, _objref_Wordy

# Wordy skeleton
__name__ = "wordyApp__POA"
class Wordy (PortableServer.Servant):
    _NP_RepositoryId = _0_wordyApp.Wordy._NP_RepositoryId


    _omni_op_d = {"login": _0_wordyApp.Wordy._d_login, "showLeaderBoard": _0_wordyApp.Wordy._d_showLeaderBoard, "top5longestWords": _0_wordyApp.Wordy._d_top5longestWords, "play": _0_wordyApp.Wordy._d_play, "nextRoundHandler": _0_wordyApp.Wordy._d_nextRoundHandler, "startTenSecondTimer": _0_wordyApp.Wordy._d_startTenSecondTimer, "startRoundTimer": _0_wordyApp.Wordy._d_startRoundTimer, "startBreakTimer": _0_wordyApp.Wordy._d_startBreakTimer, "getRoundTimer": _0_wordyApp.Wordy._d_getRoundTimer, "getBreakTimer": _0_wordyApp.Wordy._d_getBreakTimer, "addRoom": _0_wordyApp.Wordy._d_addRoom, "decreasePlayerCount": _0_wordyApp.Wordy._d_decreasePlayerCount, "deleteRoom": _0_wordyApp.Wordy._d_deleteRoom, "updatePlayerIsInGame": _0_wordyApp.Wordy._d_updatePlayerIsInGame, "updateResult": _0_wordyApp.Wordy._d_updateResult, "getWinner": _0_wordyApp.Wordy._d_getWinner, "getPlayerCount": _0_wordyApp.Wordy._d_getPlayerCount, "calculateTimeLeft": _0_wordyApp.Wordy._d_calculateTimeLeft, "getTimeLeft": _0_wordyApp.Wordy._d_getTimeLeft, "setRandomLetters": _0_wordyApp.Wordy._d_setRandomLetters, "getRoomRandomLetters": _0_wordyApp.Wordy._d_getRoomRandomLetters, "userEnteredWord": _0_wordyApp.Wordy._d_userEnteredWord, "roundWinnerChecker": _0_wordyApp.Wordy._d_roundWinnerChecker, "gameWinStateChecker": _0_wordyApp.Wordy._d_gameWinStateChecker, "getGameWinner": _0_wordyApp.Wordy._d_getGameWinner, "finishGame": _0_wordyApp.Wordy._d_finishGame, "logOffUser": _0_wordyApp.Wordy._d_logOffUser}

Wordy._omni_skeleton = Wordy
_0_wordyApp__POA.Wordy = Wordy
omniORB.registerSkeleton(Wordy._NP_RepositoryId, Wordy)
del Wordy
__name__ = "wordyApp"

#
# End of module "wordyApp"
#
__name__ = "Wordy_idl"

_exported_modules = ( "wordyApp", )

# The end.
